# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_baca_tulis_Bilangan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import locale
locale.setlocale(locale.LC_ALL, '')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(365, 165)
        MainWindow.setMinimumSize(QtCore.QSize(365, 165))
        MainWindow.setMaximumSize(QtCore.QSize(365, 165))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label.setObjectName("label")
        self.txtAngka = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAngka.setGeometry(QtCore.QRect(100, 10, 171, 20))
        self.txtAngka.setObjectName("txtAngka")
        self.tombolBaca = QtWidgets.QPushButton(self.centralwidget)
        self.tombolBaca.setGeometry(QtCore.QRect(280, 9, 75, 23))
        self.tombolBaca.setObjectName("tombolBaca")
        self.tombolTulis = QtWidgets.QPushButton(self.centralwidget)
        self.tombolTulis.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.tombolTulis.setObjectName("tombolTulis")
        self.txtHasilTulis = QtWidgets.QLineEdit(self.centralwidget)
        self.txtHasilTulis.setGeometry(QtCore.QRect(90, 101, 161, 20))
        self.txtHasilTulis.setObjectName("txtHasilTulis")
        self.tombolKeluar = QtWidgets.QPushButton(self.centralwidget)
        self.tombolKeluar.setGeometry(QtCore.QRect(280, 100, 75, 23))
        self.tombolKeluar.setObjectName("tombolKeluar")
        self.txtOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(11, 40, 341, 51))
        self.txtOutput.setObjectName("txtOutput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 365, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Keluar aplikasi
        self.tombolKeluar.clicked.connect(MainWindow.close)
        # aktifasi proses baca angka masukan
        self.tombolBaca.clicked.connect(self.BacaBilangan)
        self.txtAngka.textChanged.connect(self.BacaBilangan)
        # aktifasi proses tulis bilangan
        self.tombolTulis.clicked.connect(self.TulisBilangan)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Galih Hermawan - Baca/Tulis Bilangan"))
        self.label.setText(_translate("MainWindow", "Masukkan angka"))
        self.tombolBaca.setText(_translate("MainWindow", "Baca"))
        self.tombolTulis.setText(_translate("MainWindow", "Tulis"))
        self.tombolKeluar.setText(_translate("MainWindow", "Keluar"))
        self.txtAngka.setPlaceholderText(_translate("MainWindow", "bilangan bulat"))
        self.txtOutput.setPlaceholderText(_translate("MainWindow", "... hasil baca..."))
        self.txtHasilTulis.setPlaceholderText(_translate("MainWindow", "hasil tulis..."))
        #self.txtOutput.setEnabled(False)
        #self.txtOutput.setReadOnly(True)

    # kotak dialog kustom
    def Pesan(self, ikon, judul, teks):
        kotakPesan = QtWidgets.QMessageBox(ikon, judul, teks)
        kotakPesan.exec()
    
    # membaca bilangan dari lineEdit dan evaluasi
    def BacaBilangan(self):
        angka = self.txtAngka.text()
        if (len(angka) == 1 and angka[0] == "-") or (len(angka) == 0):
            pass
        else:
            boolValid = CekAngka(angka)
            if boolValid:
                hasil = BacaAngka(angka)
                hasil = FixBugsNol(hasil)
                self.txtOutput.setPlainText(hasil)
            else:
                self.txtAngka.backspace()
                self.Pesan(QtWidgets.QMessageBox.Warning, "Kesalahan!", "Angka masukan harus berupa bilangan bulat.")
     
    # menulis bilangan
    def TulisBilangan(self):
        teks = self.txtOutput.toPlainText()
        kalimat = teks.lower()
        kalimat = KalimatBaru(kalimat) 
        
        # cek jika ada kata minus di depan
        minus = ""
        boolMinus, kalimatBaru = self.CekMinus(kalimat)
        if boolMinus: 
            kalimat = kalimatBaru
            minus = "-"
        
        # cek komponen kalimat
        kalimat_OK = CekKalimat(kalimat)
        
        if kalimat_OK:
            #print("Kalimat asli: ", kalimat_asli)
            # pengelompokan kalimat
            kelompokKalimat = PengelompokanKalimat(kalimat)
            # evaluasi kalimat
            total = EvaluasiKalimat(kelompokKalimat)
            # luaran    
            # print("\nTotal nilai: ", total)
            # menggunakan pemisah ribuan - tergantung regional settings
            # print(f"Total nilai (lokal): {total:n}")
            strTotal = f"{total:n}"
        
            self.txtHasilTulis.setText(f"{minus}{strTotal}")
        else:
            self.Pesan(QtWidgets.QMessageBox.Warning, "Kesalahan!", "Ada komponen kalimat yang tidak terdaftar.")

        
    def CekMinus(self, kalimat):
        lstKalimat = kalimat.split()
        lstKetemu = [i for i,d in enumerate(lstKalimat) if d == "minus"]
        if lstKetemu:
            if lstKetemu[0] == 0:
                return True, " ".join(lstKalimat[1:])
        return False, None
        

if __name__ == "__main__":
    import sys
    from libBacaBilangan import BacaAngka, FixBugsNol, CekAngka
    from libTulisBilangan import PengelompokanKalimat, KalimatBaru, EvaluasiKalimat, CekKalimat
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
